import{GoogleGenAI,Modality}from'@google/genai';
const previewCache=new Map();
const pcmToWav=(base64,sampleRate=24000)=>{const raw=atob(base64),pcm=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)pcm[i]=raw.charCodeAt(i);const out=new ArrayBuffer(44+pcm.length),view=new DataView(out);const word=(o,s)=>[...s].forEach((c,i)=>view.setUint8(o+i,c.charCodeAt(0)));word(0,'RIFF');view.setUint32(4,36+pcm.length,true);word(8,'WAVE');word(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);word(36,'data');view.setUint32(40,pcm.length,true);new Uint8Array(out,44).set(pcm);return new Blob([out],{type:'audio/wav'})};
const isQuotaError=error=>/429|RESOURCE_EXHAUSTED|quota|rate.?limit/i.test(String(error?.message||error));
const friendlyError=error=>{if(isQuotaError(error))return new Error('Безплатният дневен лимит за AI гласове е изчерпан. Опитай отново след нулирането на лимита или активирай Billing в Google AI Studio.');if(/API_KEY|API key|401|403/i.test(String(error?.message||error)))return new Error('Gemini API ключът е невалиден или няма достъп до TTS модела.');return new Error('AI гласът временно не може да бъде генериран. Опитай отново след малко.')};

export class GeminiTTS{
 constructor(){this.audio=null;this.url=null}
 async request(ai,model,prompt,voiceName){const response=await ai.models.generateContent({model,contents:[{parts:[{text:prompt}]}],config:{responseModalities:[Modality.AUDIO],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName}}}}});const data=response.candidates?.[0]?.content?.parts?.find(part=>part.inlineData)?.inlineData?.data;if(!data)throw new Error('NO_AUDIO');return pcmToWav(data)}
 async generate(text,{apiKey,voiceName,rate,onProgress,onEnd,cacheKey}){this.stop();let blob=cacheKey?previewCache.get(cacheKey):null;if(!blob){const ai=new GoogleGenAI({apiKey}),pace=rate<.85?'бавно и изразително':rate>1.2?'по-бързо, но ясно':'естествено и спокойно',prompt=`Прочети следния български текст ${pace}, като професионален разказвач на аудиокнига. Не добавяй и не пропускай думи.\n\n${text}`;try{blob=await this.request(ai,'gemini-3.1-flash-tts-preview',prompt,voiceName)}catch(firstError){if(!isQuotaError(firstError))throw friendlyError(firstError);try{blob=await this.request(ai,'gemini-2.5-flash-preview-tts',prompt,voiceName)}catch(secondError){throw friendlyError(secondError)}}if(cacheKey)previewCache.set(cacheKey,blob)}this.url=URL.createObjectURL(blob);this.audio=new Audio(this.url);this.audio.playbackRate=rate;this.audio.ontimeupdate=()=>onProgress?.(this.audio.duration?this.audio.currentTime/this.audio.duration*100:0);this.audio.onended=()=>onEnd?.();await this.audio.play()}
 pause(){this.audio?.pause()}resume(){return this.audio?.play()}stop(){if(this.audio){this.audio.pause();this.audio.src='';this.audio=null}if(this.url){URL.revokeObjectURL(this.url);this.url=null}}
}
