import React from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import ErrorBoundary from './components/ErrorBoundary';
import './styles.css';
import './improvements.css';
import './ai-controls.css';
import './listening-overlay.css';
import './voice-preview.css';
import './reading-highlight.css';
import './enhancements.css';
registerSW({immediate:true});
createRoot(document.getElementById('root')).render(<React.StrictMode><ErrorBoundary><App/></ErrorBoundary></React.StrictMode>);
